#include "updater.h"
#include <algorithm>
#include <sstream>

std::string compile_object_to_structure(const Object *object)
{
  std::vector<Field> virtual_functions;
  for (auto &[key, vtf] : object->virtual_functions)
  {
    virtual_functions.push_back(vtf);
  }

  std::sort(virtual_functions.begin(), virtual_functions.end(), [](const Field &a, const Field &b)
  {
    return a.offset < b.offset;
  });

  std::vector<Field> fields;
  for (auto &[key, field] : object->fields)
  {
    fields.push_back(field);
  }

  std::sort(fields.begin(), fields.end(), [](Field a, Field b)
  {
    return a.offset < b.offset;
  });

  std::stringstream ss;
  if (object->is_class)
  {
    ss << "class ";
  }
  else
  {
    ss << "struct ";
  }
  ss << object->name;
  if (object->has_parent)
  {
    ss << " : public " << object->parent;
  }

  ss << std::endl;
  ss << "{" << std::endl;
  if (object->is_class)
  {
    ss << "public:" << std::endl;
  }

  if (!virtual_functions.empty())
  {
    auto replace_all = [](
                           const std::string &haystack,
                           const std::string &needle,
                           const std::string &replacement)
    {
      auto rep = haystack;
      if (needle.empty())
        return rep;

      size_t pos = 0;
      while ((pos = rep.find(needle, pos)) != std::string::npos)
      {
        rep.replace(pos, needle.length(), replacement);
        pos += replacement.length();
      }

      return rep;
    };

    for (size_t i = 0; i < virtual_functions.size(); i++)
    {
      auto &vtf = virtual_functions[i];
      auto is_first = (i == 0);

      uint32_t pad_amount;
      if (is_first)
      {
        pad_amount = vtf.offset;
      }
      else
      {
        auto &prev = virtual_functions[i - 1];
        pad_amount = vtf.offset - prev.offset - sizeof(void *);
      }

      auto pad_count = pad_amount / sizeof(void *);
      for (auto j = 0ul; j < pad_count; j++)
      {
        ss << "  PAD_VT();" << std::endl;
      }

      ss << "  virtual " << replace_all(vtf.type.type, "{}", vtf.name) << " = 0;";
      ss << std::endl;
    }

    ss << std::endl;
    ss << "public:";
    ss << std::endl;
  }

  for (size_t i = 0; i < fields.size(); i++)
  {
    auto &field = fields[i];
    auto is_first = (i == 0);
    auto is_last = (i == fields.size() - 1);
    if (is_first)
    {
      auto pad_amount = field.relative_offset;
      if (pad_amount)
      {
        ss << "  PAD(0x" << std::hex << field.relative_offset << ");" << std::endl;
      }
    }
    else
    {
      auto &prev = fields[i - 1];
      if ((prev.relative_offset + prev.type.size) > field.relative_offset)
      {
        LOG(ERROR, "Field " << prev.name << " overlaps " << field.name << " in object " << object->name);
      }

      auto pad_amount = field.relative_offset - prev.relative_offset - prev.type.size;
      if (pad_amount)
      {
        ss << "  PAD(0x" << std::hex << pad_amount << ");" << std::endl;
      }
    }

    ss << "  " << field.type.type << " " << field.name;
    if (field.type.arr)
    {
      ss << "[" << field.type.arr_size << "]";
    }

    ss << ";";
    ss << std::endl;

    if (is_last)
    {
      auto field_end = field.relative_offset + field.type.size;
      if (field_end < object->rel_size)
      {
        ss << " PAD(0x" << std::hex << (object->rel_size - field_end) << ");" << std::endl;
      }
    }
  }

  ss << "};" << std::endl;
  if (object->size != 0)
  {
    ss << "static_assert(sizeof(" << object->name << ") == 0x" << std::hex << object->size << ", INVALID_SIZE);" << std::endl;
  }

  for (size_t i = 0; i < fields.size(); i++)
  {
    auto &field = fields[i];
    ss << "static_assert(off(" << object->name << ", " << field.name << ") == 0x" << std::hex << field.offset << ", INVALID_OFFSET);" << std::endl;
  }
  ss << std::endl;
  return ss.str();
}

std::string compile_objects_to_header(const std::vector<Object *> &objects)
{
  std::stringstream ss;
  ss << "#pragma once" << std::endl;
  ss << "// == Generated by CachyRS updater ==" << std::endl;
  ss << "#include \"math.h\"" << std::endl;
  ss << std::endl;
  ss << "#include <EGL/egl.h>" << std::endl;
  ss << "#include <SDL2/SDL.h>" << std::endl;
  ss << std::endl;
  ss << "#include <cstdint>" << std::endl;
  ss << "#include <string>" << std::endl;
  ss << "#include <type_traits>" << std::endl;
  ss << std::endl;
  ss << "#include \"util.h\"" << std::endl;
  ss << std::endl;
  ss << "using crs::Area2;" << std::endl;
  ss << "using crs::Matrix4x4;" << std::endl;
  ss << "using crs::Vec2;" << std::endl;
  ss << "using crs::Vec3;" << std::endl;
  ss << std::endl;
  ss << "#pragma clang diagnostic push" << std::endl;
  ss << "#pragma clang diagnostic ignored \"-Wuninitialized\"" << std::endl;
  ss << "#pragma clang diagnostic ignored \"-Winvalid-offsetof\"" << std::endl;
  ss << "#pragma clang diagnostic ignored \"-Wunused-private-field\"" << std::endl;
  ss << "#pragma clang diagnostic ignored \"-Wnon-virtual-dtor\"" << std::endl;
  ss << "#pragma clang diagnostic ignored \"-Wmismatched-tags\"" << std::endl;
  ss << "#pragma clang diagnostic ignored \"-Wpadded\"" << std::endl;
  ss << std::endl;
  ss << "struct SDL_SysWMinfo;" << std::endl;
  ss << std::endl;
  ss << "#include \"reversed_util.h\"" << std::endl;
  ss << "#include \"reversed_enum.h\"" << std::endl;
  ss << "#include \"reversed_manual_base.h\"" << std::endl;
  ss << "#include \"reversed_fwd_decl.h\"" << std::endl;
  ss << "#include \"reversed_world_setting.h\"" << std::endl;
  ss << "#include \"reversed_social.h\"" << std::endl;
  ss << "#include \"reversed_render.h\"" << std::endl;
  ss << "#include \"reversed_cache.h\"" << std::endl;
  ss << "#include \"reversed_entity_update_cache.h\"" << std::endl;
  ss << "#include \"reversed_entity.h\"" << std::endl;
  ss << "#include \"reversed_local_player.h\"" << std::endl;
  ss << "#include \"reversed_var.h\"" << std::endl;
  ss << "#include \"reversed_menu.h\"" << std::endl;
  ss << "#include \"reversed_scene.h\"" << std::endl;
  ss << "#include \"reversed_widget.h\"" << std::endl;
  ss << "#include \"reversed_item_cache.h\"" << std::endl;
  ss << "#include \"reversed_network.h\"" << std::endl;
  ss << "#include \"reversed_linux.h\"" << std::endl;
  ss << "#include \"reversed_fn_decl.h\"" << std::endl;
  ss << "#include \"reversed_traits.h\"" << std::endl
     << std::endl;

  ss << "static_assert(true);" << std::endl;
  ss << "#pragma pack(push, 1)" << std::endl;
  for (auto &obj : objects)
  {
    if (obj->is_class)
    {
      ss << "class " << obj->name << ";" << std::endl;
    }
    else
    {
      ss << "struct " << obj->name << ";" << std::endl;
    }
  }

  ss << std::endl;
  for (auto obj : objects)
  {
    ss << compile_object_to_structure(obj);
  }
  ss << "#pragma pack(pop)" << std::endl;
  ss << std::endl;
  ss << "#pragma clang diagnostic pop" << std::endl;
  return ss.str();
}
