#pragma once
// == Generated by CachyRS updater ==

#pragma pack(push, 1)
struct Engine;
struct Entity;
struct Globals;
class NamedEntity;
struct NpcUpdateCache;
struct Scene003;

struct Engine
{
	PAD(0x90);
	const WindowState* window_state;
	PAD(0x46c);
	const uint32_t time;
	PAD(0x187b0);
	const Cache001* cache;
	PAD(0x7c8);
	const WidgetCache* widget_cache;
	PAD(0x28);
	const NpcUpdateCache* npc_update_cache;
	PAD(0x18);
	const PlayerUpdateCache* player_update_cache;
	PAD(0x58);
	const void* world_a;
	PAD(0x10);
	const ItemCache* item_cache;
	PAD(0x0);
	const Scene001* scene_001;
	PAD(0x5c8);
	const GameState state;
	PAD(0x4);
	const LocalPlayer* local_player;
	PAD(0x28);
	const WorldSettingCache* world_settings;
};
static_assert(off(Engine, window_state) == 0x90, INVALID_OFFSET);
static_assert(off(Engine, time) == 0x504, INVALID_OFFSET);
static_assert(off(Engine, cache) == 0x18cb8, INVALID_OFFSET);
static_assert(off(Engine, widget_cache) == 0x19488, INVALID_OFFSET);
static_assert(off(Engine, npc_update_cache) == 0x194b8, INVALID_OFFSET);
static_assert(off(Engine, player_update_cache) == 0x194d8, INVALID_OFFSET);
static_assert(off(Engine, world_a) == 0x19538, INVALID_OFFSET);
static_assert(off(Engine, item_cache) == 0x19550, INVALID_OFFSET);
static_assert(off(Engine, scene_001) == 0x19558, INVALID_OFFSET);
static_assert(off(Engine, state) == 0x19b28, INVALID_OFFSET);
static_assert(off(Engine, local_player) == 0x19b30, INVALID_OFFSET);
static_assert(off(Engine, world_settings) == 0x19b60, INVALID_OFFSET);

struct Entity
{
	PAD(0x10);
	const EntityType type;
	PAD(0x46);
	char Entity_type_end;
};
static_assert(off(Entity, type) == 0x10, INVALID_OFFSET);
static_assert(off(Entity, Entity_type_end) == 0x57, INVALID_OFFSET);

struct Globals
{
	PAD(0xf39b0);
	char menu_action_handler_widget;
	PAD(0x6e17f);
	char menu_action_handler_walk;
	PAD(0xa6f);
	char menu_action_handler_npc7;
	PAD(0x2f);
	char menu_action_handler_npc6;
	PAD(0x1f);
	char menu_action_handler_npc5;
	PAD(0x1f);
	char menu_action_handler_npc4;
	PAD(0x1f);
	char menu_action_handler_npc3;
	PAD(0x1f);
	char menu_action_handler_npc2;
	PAD(0x1f);
	char menu_action_handler_npc1;
	PAD(0x2d2df);
	char menu_execute;
	PAD(0xb552f);
	char render_widget;
	PAD(0x92b5af);
	char engine_tick;
	PAD(0x14a05f);
	char heap_alloc;
	PAD(0x1dcaf);
	char heap_alloc_aligned;
	PAD(0x770daf);
	Engine* engine;
	PAD(0x249fa0);
	Linux001* linux_001;
	PAD(0xe290);
	void* heap;
};
static_assert(off(Globals, menu_action_handler_widget) == 0xf39b0, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_walk) == 0x161b30, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc7) == 0x1625a0, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc6) == 0x1625d0, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc5) == 0x1625f0, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc4) == 0x162610, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc3) == 0x162630, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc2) == 0x162650, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc1) == 0x162670, INVALID_OFFSET);
static_assert(off(Globals, menu_execute) == 0x18f950, INVALID_OFFSET);
static_assert(off(Globals, render_widget) == 0x244e80, INVALID_OFFSET);
static_assert(off(Globals, engine_tick) == 0xb70430, INVALID_OFFSET);
static_assert(off(Globals, heap_alloc) == 0xcba490, INVALID_OFFSET);
static_assert(off(Globals, heap_alloc_aligned) == 0xcd8140, INVALID_OFFSET);
static_assert(off(Globals, engine) == 0x1448ef0, INVALID_OFFSET);
static_assert(off(Globals, linux_001) == 0x1692e98, INVALID_OFFSET);
static_assert(off(Globals, heap) == 0x16a1130, INVALID_OFFSET);

class NamedEntity : public Entity
{
public:
	PAD(0x38);
	const JString name;
	PAD(0x1c8);
	const Vec3<float> position;
	PAD(0x4c);
	const JArray<const uint32_t> animation_queue;
	PAD(0xc20);
	const EntityStatus* status;
};
static_assert(off(NamedEntity, name) == 0x90, INVALID_OFFSET);
static_assert(off(NamedEntity, position) == 0x270, INVALID_OFFSET);
static_assert(off(NamedEntity, animation_queue) == 0x2c8, INVALID_OFFSET);
static_assert(off(NamedEntity, status) == 0xef8, INVALID_OFFSET);

struct NpcUpdateCache
{
	PAD(0x10);
	const NpcUpdate** npcs;
	PAD(0x0);
	const uint64_t size;
	PAD(0xb080);
	const uint32_t valid_count;
};
static_assert(off(NpcUpdateCache, npcs) == 0x10, INVALID_OFFSET);
static_assert(off(NpcUpdateCache, size) == 0x18, INVALID_OFFSET);
static_assert(off(NpcUpdateCache, valid_count) == 0xb0a0, INVALID_OFFSET);

struct Scene003
{
	PAD(0x10170);
	const WorldNode* world_root;
	PAD(0x3088);
	const Matrix4x4 projection_matrix;
};
static_assert(off(Scene003, world_root) == 0x10170, INVALID_OFFSET);
static_assert(off(Scene003, projection_matrix) == 0x13200, INVALID_OFFSET);

#pragma pack(pop)
