#pragma once
// == Generated by CachyRS updater ==

#pragma pack(push, 1)
struct Globals;
struct Engine;
struct Scene003;
struct Entity;
class NamedEntity;
class Player;
class Npc;
struct NpcUpdateCache;

struct Globals
{
  PAD(0xf4320);
  char menu_action_handler_widget0;
  PAD(0x14f);
  char menu_action_handler_widget1;
  PAD(0x32c8f);
  char menu_action_handler_widget2;
  PAD(0x42cff);
  char menu_action_handler_walk;
  PAD(0x7ef);
  char menu_action_handler_npc6;
  PAD(0x1f);
  char menu_action_handler_npc5;
  PAD(0x1f);
  char menu_action_handler_npc4;
  PAD(0x1f);
  char menu_action_handler_npc3;
  PAD(0x1f);
  char menu_action_handler_npc2;
  PAD(0x1f);
  char menu_action_handler_npc1;
  PAD(0x1f);
  char menu_action_handler_npc0;
  PAD(0x39f);
  char menu_action_handler_obj6;
  PAD(0x1f);
  char menu_action_handler_obj5;
  PAD(0x1f);
  char menu_action_handler_obj4;
  PAD(0x1f);
  char menu_action_handler_obj3;
  PAD(0x1f);
  char menu_action_handler_obj2;
  PAD(0x1f);
  char menu_action_handler_obj1;
  PAD(0x1f);
  char menu_action_handler_obj0;
  PAD(0x2b05f);
  char menu_execute;
  PAD(0xc9cf);
  char add_chat_message;
  PAD(0x3278f);
  char add_menu_option;
  PAD(0x7a4af);
  char render_widget;
  PAD(0x43d1df);
  char set_varbit;
  PAD(0x551d4f);
  char engine_tick;
  PAD(0xae24f);
  char heap_alloc;
  PAD(0x5b5bf);
  char heap_alloc_aligned;
  PAD(0x772f17);
  Engine* engine;
  PAD(0x249318);
  Linux001* linux_001;
  PAD(0xe290);
  void* heap;
};
static_assert(off(Globals, menu_action_handler_widget0) == 0xf4320, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_widget1) == 0xf4470, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_widget2) == 0x127100, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_walk) == 0x169e00, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc6) == 0x16a5f0, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc5) == 0x16a610, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc4) == 0x16a630, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc3) == 0x16a650, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc2) == 0x16a670, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc1) == 0x16a690, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_npc0) == 0x16a6b0, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_obj6) == 0x16aa50, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_obj5) == 0x16aa70, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_obj4) == 0x16aa90, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_obj3) == 0x16aab0, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_obj2) == 0x16aad0, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_obj1) == 0x16aaf0, INVALID_OFFSET);
static_assert(off(Globals, menu_action_handler_obj0) == 0x16ab10, INVALID_OFFSET);
static_assert(off(Globals, menu_execute) == 0x195b70, INVALID_OFFSET);
static_assert(off(Globals, add_chat_message) == 0x1a2540, INVALID_OFFSET);
static_assert(off(Globals, add_menu_option) == 0x1d4cd0, INVALID_OFFSET);
static_assert(off(Globals, render_widget) == 0x24f180, INVALID_OFFSET);
static_assert(off(Globals, set_varbit) == 0x68c360, INVALID_OFFSET);
static_assert(off(Globals, engine_tick) == 0xbde0b0, INVALID_OFFSET);
static_assert(off(Globals, heap_alloc) == 0xc8c300, INVALID_OFFSET);
static_assert(off(Globals, heap_alloc_aligned) == 0xce78c0, INVALID_OFFSET);
static_assert(off(Globals, engine) == 0x145a7d8, INVALID_OFFSET);
static_assert(off(Globals, linux_001) == 0x16a3af8, INVALID_OFFSET);
static_assert(off(Globals, heap) == 0x16b1d90, INVALID_OFFSET);

struct Engine
{
  PAD(0x504);
  uint32_t time;
  PAD(0x187d0);
  Cache001* cache;
  PAD(0x7c8);
  WidgetCache* widget_cache;
  PAD(0x20);
  Menu* menu;
  PAD(0x0);
  NpcUpdateCache* npc_update_cache;
  PAD(0x18);
  PlayerUpdateCache* player_update_cache;
  PAD(0x18);
  SocialCache* social_cache;
  PAD(0x38);
  void* world_a;
  PAD(0x10);
  ItemCache* item_cache;
  PAD(0x0);
  Scene001* scene_001;
  PAD(0x5c8);
  GameState state;
  PAD(0x4);
  LocalPlayer* local_player;
  PAD(0x8);
  WorldSettingCache world_settings;
};
static_assert(off(Engine, time) == 0x504, INVALID_OFFSET);
static_assert(off(Engine, cache) == 0x18cd8, INVALID_OFFSET);
static_assert(off(Engine, widget_cache) == 0x194a8, INVALID_OFFSET);
static_assert(off(Engine, menu) == 0x194d0, INVALID_OFFSET);
static_assert(off(Engine, npc_update_cache) == 0x194d8, INVALID_OFFSET);
static_assert(off(Engine, player_update_cache) == 0x194f8, INVALID_OFFSET);
static_assert(off(Engine, social_cache) == 0x19518, INVALID_OFFSET);
static_assert(off(Engine, world_a) == 0x19558, INVALID_OFFSET);
static_assert(off(Engine, item_cache) == 0x19570, INVALID_OFFSET);
static_assert(off(Engine, scene_001) == 0x19578, INVALID_OFFSET);
static_assert(off(Engine, state) == 0x19b48, INVALID_OFFSET);
static_assert(off(Engine, local_player) == 0x19b50, INVALID_OFFSET);
static_assert(off(Engine, world_settings) == 0x19b60, INVALID_OFFSET);

struct Scene003
{
  PAD(0x10170);
  WorldNode* world_root;
  PAD(0x3088);
  Matrix4x4 projection_matrix;
};
static_assert(off(Scene003, world_root) == 0x10170, INVALID_OFFSET);
static_assert(off(Scene003, projection_matrix) == 0x13200, INVALID_OFFSET);

struct Entity
{
  PAD(0x18);
  WorldNode* parent;
  PAD(0x0);
  EntityType type;
  PAD(0x3f);
  Terrain* terrain;
};
static_assert(sizeof(Entity) == 0x68, INVALID_SIZE);
static_assert(off(Entity, parent) == 0x18, INVALID_OFFSET);
static_assert(off(Entity, type) == 0x20, INVALID_OFFSET);
static_assert(off(Entity, terrain) == 0x60, INVALID_OFFSET);

class NamedEntity : public Entity
{
public:
  PAD(0x20);
  int32_t server_index;
  PAD(0x4);
  JString name;
  PAD(0x1c0);
  MovementQueue* movement_queue;
  PAD(0x0);
  Vec3<float> position;
  PAD(0x4c);
  JVector<const uint32_t> animation_queue;
  PAD(0xc18);
  EntityStatus* status;
 PAD(0x154);
};
static_assert(sizeof(NamedEntity) == 0x1054, INVALID_SIZE);
static_assert(off(NamedEntity, server_index) == 0x88, INVALID_OFFSET);
static_assert(off(NamedEntity, name) == 0x90, INVALID_OFFSET);
static_assert(off(NamedEntity, movement_queue) == 0x268, INVALID_OFFSET);
static_assert(off(NamedEntity, position) == 0x270, INVALID_OFFSET);
static_assert(off(NamedEntity, animation_queue) == 0x2c8, INVALID_OFFSET);
static_assert(off(NamedEntity, status) == 0xef8, INVALID_OFFSET);

class Player : public NamedEntity
{
public:
  PAD(0x14);
  Model* model;
  PAD(0x2c);
  int32_t combat_level;
  PAD(0x8);
  int32_t skill_level;
 PAD(0x244);
};
static_assert(sizeof(Player) == 0x12f0, INVALID_SIZE);
static_assert(off(Player, model) == 0x1068, INVALID_OFFSET);
static_assert(off(Player, combat_level) == 0x109c, INVALID_OFFSET);
static_assert(off(Player, skill_level) == 0x10a8, INVALID_OFFSET);

class Npc : public NamedEntity
{
public:
  PAD(0xc);
  int32_t cache_id;
  PAD(0xf4);
  uint32_t visible_level;
 PAD(0x26);
};
static_assert(sizeof(Npc) == 0x1182, INVALID_SIZE);
static_assert(off(Npc, cache_id) == 0x1060, INVALID_OFFSET);
static_assert(off(Npc, visible_level) == 0x1158, INVALID_OFFSET);

struct NpcUpdateCache
{
  PAD(0x10);
  NpcUpdate** npcs;
  PAD(0x0);
  uint64_t size;
  PAD(0xb080);
  uint32_t valid_count;
};
static_assert(off(NpcUpdateCache, npcs) == 0x10, INVALID_OFFSET);
static_assert(off(NpcUpdateCache, size) == 0x18, INVALID_OFFSET);
static_assert(off(NpcUpdateCache, valid_count) == 0xb0a0, INVALID_OFFSET);

#pragma pack(pop)
